CREATE DATABASE IF NOT EXISTS db;
CREATE TABLE IF NOT EXISTS db.Categories(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	categoryName VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS db.Products(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	productName VARCHAR(50) NOT NULL,
	productInfo VARCHAR(100) NOT NULL,
	productIMG VARCHAR(50) NOT NULL,
	productPrice float NOT NULL
);
