apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports: 
  - protocol: TCP
    port: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: alinadenisa/onlinestore-db:latest4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
