apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: alinadenisa/flask-app:latest01
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: "mysql+pymysql://root:password@db/db"
        - name: SECRET_KEY
          value: "mysecretkey"  
